### ISSUE TITLE
Why Berlin?

### ISSUE THREAD

**Issue by sachinr** [sachinr/meeting-time#3]
Lets change this to Paris.

| commit | file reference | pull request |  |
| --- | --- | --- | --- |
| 81f69719723d51b422622ccf6f1e8c753aafcfbc | [assets/scripts/url.js#L25](https://github.com/sachinr/homeslice/blob/81f69719723d51b422622ccf6f1e8c753aafcfbc/assets/scripts/url.js#L25) | #1 | [![#1](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/sachinr/homeslice/pull/1) |

**Comment by davideg** [comment]
This is a good point. Why not Paris?
